### ISSUE TITLE
ERROR in ./node_modules/angular2-json2csv/src/csv.service.ts

### ISSUE THREAD

**Issue by azguindou** [aqeel-legalinc/angular2-json2csv#11]
I want to use angular-2-jsoncvs in my angular 5 project but this error was appeared:
```
ERROR in ./node_modules/angular2-json2csv/src/csv.service.ts
Module build failed: Error: C:\dev\CFinder\CFinderFront\node_modules\angular2-json2csv\src\csv.service.ts is not part of the compilation output. Please check the other error mes
sages for details.
    at AngularCompilerPlugin.getCompiledFile (C:\dev\CFinder\CFinderFront\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:649:23)
    at plugin.done.then (C:\dev\CFinder\CFinderFront\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./node_modules/angular2-json2csv/index.js 2:20-48
 @ ./src/app/crossreview/crossreview.component.ts
 @ ./src/app/components/sidemenu/sidemenu.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

**Comment by kkajdd** [comment]
the same error for me as well.

**Comment by Anujmoglix** [comment]
any response ?

**Comment by artrepubliq** [comment]
add "csv.service.ts" to tsconfig.spec.json under "files". It worked for me.

**Comment by azmatzuberi** [comment]
I get this error now, even though it is included in the tsconfig.spec.json file:

ERROR in ./node_modules/angular2-json2csv/src/csv.service.ts
Module build failed: Error: C:\Users\zuberiaz\OneDrive - Government of Ontario\Documents\spapp\sp-app\node_modules\angular2-json2csv\src\csv.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Users\zuberiaz\OneDrive - Government of Ontario\Documents\spapp\sp-app\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:708:23)
    at plugin.done.then (C:\Users\user\Documents\spapp\sp-app\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by mohaqqani** [comment]
Facing same error, any update or work around ?
